// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHsJI3v63EAPFCwLJ1x4ByAY08LMauYs',
    appId: '1:924952529655:web:928e80b6c9de6e05aa21f2',
    messagingSenderId: '924952529655',
    projectId: 'crud-ecc07',
    authDomain: 'crud-ecc07.firebaseapp.com',
    storageBucket: 'crud-ecc07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZppaI_Ogl9eAY0nB9Gf2FTYqHC2AHKzE',
    appId: '1:924952529655:android:5dc0489a1a940c76aa21f2',
    messagingSenderId: '924952529655',
    projectId: 'crud-ecc07',
    storageBucket: 'crud-ecc07.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoHsJI3v63EAPFCwLJ1x4ByAY08LMauYs',
    appId: '1:924952529655:web:e90f792947c0eefcaa21f2',
    messagingSenderId: '924952529655',
    projectId: 'crud-ecc07',
    authDomain: 'crud-ecc07.firebaseapp.com',
    storageBucket: 'crud-ecc07.firebasestorage.app',
  );
}
